#! /usr/bin/env python

# Copyright (c) 2010 Ben Olive
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

## Config
# Set to True to use RPC false to use a unix socket
rpc=False
# Port to send notifications to
port=2199
# File to use for IPC if using Unix Domain Sockets
ipcFile='~/.pynotify.sock'

import xmlrpclib
import sys
import socket
import os


if len(sys.argv) < 2:
    print "USAGE: %s <message>" % sys.argv[0]
    sys.exit(-1)

sys.argv.pop(0)
# Use all passed in args as a message
message = ' '.join(sys.argv)

if rpc:
    notificationPane = xmlrpclib.ServerProxy("http://localhost:%d" % port)
    notificationPane.show(message)
else:
    ipcFile=os.path.expanduser(ipcFile)
    client = socket.socket(socket.AF_UNIX,socket.SOCK_DGRAM)
    client.sendto('S' + message, ipcFile)
